module.exports = {
  financeArea: [
    {
      type: 'autogenerated', 
      dirName: 'finance-area'
    }
  ],
  erpHome: [
    {
      type: 'autogenerated', 
      dirName: 'erp-home'
    }
  ],
  planning: [
    {
      type: 'autogenerated', 
      dirName: 'planning'
    }
  ],
  production: [
    {
      type: 'autogenerated', 
      dirName: 'production'
    }
  ],
  ddmrp: [
    {
      type: 'autogenerated', 
      dirName: 'ddmrp'
    }
  ],
  crm: [
    {
      type: 'autogenerated', 
      dirName: 'crm'
    }
  ],
  purchase: [
    {
      type: 'autogenerated', 
      dirName: 'purchase'
    }
  ],
  sales: [
    {
      type: 'autogenerated', 
      dirName: 'sales'
    }
  ],
  treasury: [
    {
      type: 'autogenerated', 
      dirName: 'treasury'
    }
  ],
  logistics: [
    {
      type: 'autogenerated', 
      dirName: 'logistics'
    }
  ],
  subcontractor: [
    {
      type: 'autogenerated', 
      dirName: 'subcontractor'
    }
  ],
  configurations: [
    {
      type: 'autogenerated', 
      dirName: 'configurations'
    }
  ],
  formNavigator: [
    {
      type: 'autogenerated', 
      dirName: 'form-navigator'
    }
  ],
  objectNavigator: [
    {
      type: 'autogenerated', 
      dirName: 'object-navigator'
    }
  ],
  panels: [
    {
      type: 'autogenerated', 
      dirName: 'panels'
    }
  ],
  projectManagement: [
    {
      type: 'autogenerated', 
      dirName: 'project-management'
    }
  ],
  quality: [
    {
      type: 'autogenerated', 
      dirName: 'quality'
    }
  ],
  controlling: [
    {
      type: 'autogenerated', 
      dirName: 'controlling'
    }
  ],
  guide: [
    {
      type: 'autogenerated', 
      dirName: 'guide'
    }
  ],
  applications: [
    {
      type: 'autogenerated', 
      dirName: 'applications'
    }
  ],
  knowlegdeBase: [
    {
      type: 'autogenerated', 
      dirName: 'knowlegde-base'
    }
  ],
  video: [
      {
        type: 'autogenerated', 
        dirName: 'video'
      }
  ],
  releaseNotes: [
    {
      type: 'autogenerated', 
      dirName: 'release-notes'
    }
  ], 
};
