name: Daily Integration (website-edits)

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  integrate-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ensure the workflow has write permissions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Synchronize website-edits with main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # Fetch all branches
        git fetch --all

        # Checkout website-edits branch
        git checkout website-edits

        # Pull the latest changes from origin/website-edits
        git pull origin website-edits

        # Merge main into website-edits
        git merge origin/main -m "Sync website-edits with main"

        # Push the synchronized website-edits branch back to the remote
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git website-edits

    - name: Merge website-edits into main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Checkout main branch
        git checkout main
        git pull origin main

        # Merge website-edits into main
        git merge --no-ff origin/website-edits -m "Daily merge of website-edits into main"

        # Push the changes to the main branch
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
